### ISSUE TITLE
Custom Layout Not Working

### ISSUE THREAD

**Issue by flensburger88** [Aigent/log4js-logstash-tcp#2]
Hello,
I tried to apply a custom layout, but it didn't work.
my configuration looks like the following 

` "logstash": {
      "type": "log4js-logstash",
      "host": "xxxx",
      "port": 5047,
      "layout": { "type": "json", "separator": "" },
      "debug" : true
    }`
from a short look into the source, this happens because of "index.js" the line "layout = null",
effects that in the method `logstashAppender` => `layout = layout || logstashLayout;` allways takes the default layout.

In the original project logstashudp, this was allready fixed.
https://github.com/log4js-node/logstashUDP/blob/master/src/index.js 
`if (config.layout) {
    layout = layouts.layout(config.layout.type, config.layout);
}`

Would it be possible to apply this fix?
Thank´s

**Comment by degola** [comment]
Hey, would you mind to do a pull-request for that change?

**Comment by degola** [comment]
the issue should be solved now.
