### ISSUE TITLE
Memory leak in the TcpConnectionPool.js

### ISSUE THREAD

**Issue by aka-rider** [Aigent/log4js-logstash-tcp#3]
The following line creates `Timeout` objects indefinitely.

~~~js
setTimeout(() => {self.realSend(message);}, this.connectionNotReadyRetryInterval);
~~~

At some point, `clearTimeout` should be called for every created `Timeout` object, otherwise memory consumption grows indefinitely, as a CPU consumption in the `processTimers` node.js function.

**Comment by degola** [comment]
thanks for contributing, changed implementation accordingly.
